version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lawgic_db
      POSTGRES_USER: lawgic_user
      POSTGRES_PASSWORD: lawgic_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lawgic_user -d lawgic_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: